gaia-taipei/tw-firefox-weekly

dwi2.md
[W51] dwi2: 2014-12-15 ~ 2014-12-19
=> [W51] dwi2: 2014-12-15 ~ 2014-12-19

dwi2.md
[W52] dwi2: 2014-12-22 ~ 2014-12-26
[W53] dwi2: 2014-12-29 ~ 2014-12-31
=> [W52][W53] dwi2: 2014-12-22 ~ 2014-12-31

dwi2.md
[W2] dwi2: 2015-1-5 ~ 2015-1-9
=> [W2] dwi2: 2015-1-5 ~ 2015-1-9

dwi2.md
[W3] dwi2: 2015-1-12 ~ 2015-1-16
=> [W3] dwi2: 2015-1-12 ~ 2015-1-16

JohnHu.md
=> [W03] John Hu: 01/12 - 01/16

dwi2.md
因為上週[W3]的尚未merge, 所以此包PR包含兩個commit
[W3] dwi2: 2015-1-12 ~ 2015-1-16
[W4] dwi2: 2015-1-19 ~ 2015-1-23
=> [W4] dwi2: 2015-1-19 ~ 2015-1-23

Luke.md
*Note*: There are two commits in this PR
=> [W05][W06] Luke: 01/26 - 02/06 (two weeks)

dwi2.md
[W5] dwi2: 2015-1-26 ~ 2015-1-30
=> [W05] dwi2: 2015-1-26 ~ 2015-1-30

dwi2.md
We have two commits in this PR, because weekly report of last week is not merged yet, .
=> [W6] dwi2: 2015-2-2 ~ 2015-2-6

Luke.md
There are two commits in this PR.
=> [W07][W08] Luke: 02/09 - 02/17

dwi2.md
[W7][W8] dwi2: 2015-2-9 ~ 2015-2-17
=> [W7][W8] dwi2: 2015-2-9 ~ 2015-2-17

dwi2.md
[W9] dwi2: 2015-2-24 ~ 2015-2-26
=> [W9] dwi2: 2015-2-24 ~ 2015-2-26

dwi2.md
[W10] dwi2: 2015-3-2 ~ 2015-3-6
=> [W10] dwi2: 2015-3-2 ~ 2015-3-6

dwi2.md
[W11] dwi2: 2015-3-9 ~ 2015-3-13
=> [W11] dwi2: 2015-3-9 ~ 2015-3-13

dwi2.md
[W12] dwi2: 2015-3-16 ~ 2015-3-20
=> [W12] dwi2: 2015-3-16 ~ 2015-3-20

PYChen.md
=> [W12] PYChen: 03/16 - 03/21

dwi2.md
[W13] dwi2: 2015-3-23 ~ 2015-3-27
=> [W13] dwi2: 2015-3-23 ~ 2015-3-27

PYChen.md
[W13] PYChen: 2015-3-23 ~ 2015-3-27
=> [W13] PYChen: 2015-3-23 ~ 2015-3-27

dwi2.md
[W14] dwi2: 2015-3-30 ~ 2015-4-3
=> [W14] dwi2: 2015-3-30 ~ 2015-4-3

dwi2.md
[W15] dwi2: 2015-4-6 ~ 2015-4-10
=> [W15] dwi2: 2015-4-6 ~ 2015-4-10

dwi2.md
[W16] dwi2: 2015-4-13 ~ 2015-4-17
=> [W16] dwi2: 2015-4-13 ~ 2015-4-17

dwi2.md
[W17] dwi2: 2015-4-20 ~ 2015-4-24
=> [W17] dwi2: 2015-4-20 ~ 2015-4-24

dwi2.md
[W18] dwi2: 2015-4-25 ~ 2015-4-29
=> [W18] dwi2: 2015-4-25 ~ 2015-4-29

dwi2.md
[W19] dwi2: 2015-5-4 ~ 2015-5-8
=> [W19] dwi2: 2015-5-4 ~ 2015-5-8

dwi2.md
[W20] dwi2: 2015-5-11 ~ 2015-5-15
=> [W20] dwi2: 2015-5-11 ~ 2015-5-15

dwi2.md
[W21] dwi2: 2015-5-18 ~ 2015-5-22
=> [W21] dwi2: 2015-5-18 ~ 2015-5-22

dwi2.md
[W22] dwi2: 2015-5-25 ~ 2015-5-29
=> [W22] dwi2: 2015-5-25 ~ 2015-5-29

dwi2.md
[W23] dwi2: 2015-6-1 ~ 2015-6-5
[W24] dwi2: 2015-6-8 ~ 2015-6-12
=> [W23][W24] dwi2: 2015-6-1 ~ 2015-6-12

dwi2.md
[W25][W26][W27] dwi2: 2015-6-15 ~ 2015-7-3
=> [W25][W26][W27] dwi2: 2015-6-15 ~ 2015-7-3

dwi2.md
[W28] dwi2: 2015-7-6 ~ 2015-7-10
=> [W28] dwi2: 2015-7-6 ~ 2015-7-10

rex_lee.md
=> [W28] Rex: 07/06 - 07/10

dwi2.md
[W29] dwi2: 2015-7-13 ~ 2015-7-17
=> [W29] dwi2: 2015-7-13 ~ 2015-7-17

dwi2.md
[W30] dwi2: 2015-7-20 ~ 2015-7-24
=> [W30] dwi2: 2015-7-20 ~ 2015-7-24

dwi2.md
[W31] dwi2: 2015-7-27 ~ 2015-7-31
=> [W31] dwi2: 2015-7-27 ~ 2015-7-31

dwi2.md
[W32] dwi2: 2015-8-3 ~ 2015-8-7
=> [W32] dwi2: 2015-8-3 ~ 2015-8-7

evanxd.md
=> [W32] evanxd: 2015-8-3 ~ 2015-8-7

GregWeng.md
@timdream I've updated the report.
=> [W32] Greg: 2015-8-3 ~ 2015-8-7

evanxd.md
=> [W33] evanxd: 2015-8-10 ~ 2015-8-14

dwi2.md
[W33] dwi2: 2015-8-10 ~ 2015-8-14
=> [W33] dwi2: 2015-8-10 ~ 2015-8-14

dwi2.md
[W34] dwi2: 2015-8-17 ~ 2015-8-21
My final weekly report. Farewell!
=> [W34] dwi2: 2015-8-17 ~ 2015-8-21

evanxd.md
=> [W34] evanxd: 2015-8-17 ~ 2015-8-21

GregWeng.md
=> [W34] Greg Weng: 08/17 - 08/21

SteveChung.md
Report for result in last week and plan for this week
=>  [W34] SteveChung 2015-8-17 ~ 2015-8-21

evanxd.md
@timdream, I've updated my report.
=> [W35] evanxd: 2015-8-24 ~ 2015-8-28

GregWeng.md
@timdream 
Finally write them down... Sorry for the delay.
=> [W35] GregWeng 2015-8-31 ~ 2015-9-4

evanxd.md
=> [W36] evanxd: 2015-8-31 ~ 2015-9-4

evanxd.md
=> [W37] evanxd: 2015-9-7 ~ 2015-9-11

GregWeng.md
=> [w37] Greg Weng 09-07 ~ 09-11

GregWeng.md
=> [Q3Q4] Greg Weng

Luke.md
**Note**: This PR comes in two weekly reports.
=> [W39][W40] Luke: 09/21 - 09/25, 09/30 - 10/02

evanxd.md
=> [W42] evanxd: 10/12 - 10/16

evanxd.md
=> [W43] evanxd: 10/19 - 10/23

GregWeng.md
@timdream I modify the format according to the measures
=> [w43] GregWeng: 10/19 ~ 10/23

FredLin.md
change Q4 Goals. `low storage` is descoped from 2.5 so will change to measure any feature that during this time frame
=> [w43] FredLin: 10/19 ~ 10/23

GregWeng.md
=> [W44] 10/26 ~ 10/30

evanxd.md
=> [W44] evanxd: 10/26 - 10/30

evanxd.md
@timdream, I've updated the report. Because of attending MozFest, sent the report lately.
=> [W45] evanxd: 11/02 - 11/06

GregWeng.md
=> [W47][W48] Greg: 11/16 - 11/20, 11/23 - 11/27

evanxd.md
=> [W46][W47][W48] evanxd: 11/09 - 11/27

evanxd.md
=> [W50] evanxd: 12/07 - 12/11

evanxd.md
=> [W51] evanxd: 12/14 - 12/18

ScottWu.md
Removed some old tasks that won't be worked on anymore.
=> [2016 w5 & w7] Scott Wu

evanxd.md
@timdream, Updated the report.
=> [W07] evanxd: 2/15 - 2/19

TDC-Firefox-Weekly-Buglist.md
update Tim's team first, will perform that for Evelyn's team later
=> w20 update - Tim's team

ScottWu.md
Combined status update for W38 & W39. Apologies for the delay. Thanks!
=> [W38-W39] Scott Wu: 9/19 ~ 9/30

MaxLiu.md
=> [W45] Max Liu: 11/07 ~ 11/11

Luke.md
Note that there are three commits attached.
=> [W48-50] Luke: 11/28 - 12/16

walkingice.md
=> Walkingice

walkingice.md
=> W10~W14: Julian's Report

MaxLiu.md
[W10~12] Max Liu: 03/06 ~ 03/24
[W13~14] Max Liu: 03/27 ~ 04/07
=> [W11~14] Max Liu: 03/06 ~ 04/07
